habeame_esta/habeame_esta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

habeame_esta/home/urls.py
from django.urls import path, include
from .views import HabeasFormView

urlpatterns = [
    path('', HabeasFormView.as_view(), name='home-index-generator')
]

habeame_esta/home/models.py
from django.db import models
from datetime import date, time
import locale
# Create your models here.

class Habeas:
    def __init__(self, presenter_fullname: str, presenter_document_type: str, presenter_document_number: str, presenter_address: str, event_date: date, detained_fullname: str, detained_detention_address: str, detained_detention_time: time):
        self.presenter_fullname = presenter_fullname
        self.presenter_document_type = presenter_document_type
        self.presenter_document_number = presenter_document_number
        self.presenter_address = presenter_address
        self.event_date = event_date
        self.detained_fullname = detained_fullname
        self.detained_detention_address = detained_detention_address
        self.detained_detention_time = detained_detention_time

    def for_template(self):
        locale.setlocale(locale.LC_ALL, 'es_PE.UTF-8')
        return {
            'fecha_hoy': date.today().strftime('%d de %B'),
            'nombre_presentante': self.presenter_fullname,
            'tipo_documento': self.presenter_document_type,
            'numero_documento': self.presenter_document_number,
            'domicilio': self.presenter_address,
            'fecha_marcha': self.event_date,
            'nombre_detenido': self.detained_fullname,
            'lugar_incidente': self.detained_detention_address,
            'hora': self.detained_detention_time.strftime('%H:%M')
        }

habeame_esta/home/forms.py
from django import forms

class HabeasForm(forms.Form):

    presenter_fullname = forms.CharField()
    presenter_document_type = forms.CharField()
    presenter_document_number = forms.CharField()
    presenter_address = forms.CharField()

    event_date = forms.CharField()

    detained_fullname = forms.CharField()
    detained_detention_address = forms.CharField()
    detained_detention_time = forms.TimeField()

habeame_esta/home/views.py
from django.shortcuts import render
from .forms import HabeasForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.http import HttpResponse

from .generator import HabeasGenerator

class HabeasFormView(FormView):
    form_class = HabeasForm
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):   
        # called whenever the pages is rendered       
        context = super().get_context_data(**kwargs)                     
        context["days_list"] = [
            '14 de Noviembre',
            '15 de Noviembre',
            '21 de Noviembre'
        ]
        return context

    def form_valid(self, form):
        return self.generate_habeas(form.cleaned_data)

    def generate_habeas(self, valid_data):
        print(valid_data)
        generator = HabeasGenerator(valid_data)
        generated_file = generator.generate_document()
        response = HttpResponse(generated_file, content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
        response['Content-Disposition'] = 'attachment; filename="habeas_corpus.docx"'
        return response

habeame_esta/home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset utf-8>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link href="{% static 'home/css/style.css' %}" text="text/css" rel="stylesheet" media="">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap" rel="stylesheet">


    <title>Habéame Esta - Hábeas Corpus Formulario</title>
</head>

<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-auto">
                <div align="center">
                    <img class="logo" src="{% static 'home/img/logo_habeame_esta.png' %}">
                </div>
                {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <form action="." method="post" class="presentante">
                    {% csrf_token %}
                    <p class="titulo">Ingresa tu información como Presentante</p>
                    <!-- NOMBRES DEL PRESENTANTE -->
                    <div class="nombres form-group">
                        <label class="etiqueta" for="presenter_fullname">Nombres y Apellidos</label>
                        <br>
                        <input id="id_presenter_fullname" name="presenter_fullname" type="text" pattern="[A-zñ' ]+"
                            placeholder="Ingrese aquí" required>
                    </div>

                    <!-- DOCUMENTO DE IDENTIDAD -->
                    <div class="form-group">
                        <p class="etiqueta">Tipo de Documento</p>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="presenter_document_type" id="exampleRadios1"
                            value="DNI" required>
                        <label class="form-check-label" for="presenter_document_type">
                            DNI
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="presenter_document_type" id="exampleRadios2"
                            value="CE">
                        <label class="form-check-label" for="presenter_document_type">
                            CE
                        </label>
                    </div>

                    <!-- Numero del Documento de IDENTIDAD -->

                    <div class="Ndoc form-group">
                        <br>
                        <input id="id_presenter_document_number" class="NroDocumento" type="text"
                            name="presenter_document_number" placeholder="Nro de Documento" required>
                        <br>
                    </div>

                    <!-- DOMICILIO DEL PRESENTANTE -->
                    <div class="form-group domicilio">
                        <label for="presenter_address" class="etiqueta">Domicilio</label>
                        <input name="presenter_address" type="text" class="form-control" id="id_presenter_address"
                            placeholder="Av. los Cipreses #1.... Los Olivos - Lima" required>
                    </div>
                    <br>


                    <!-- FECHA DE LA MANIFESTACION -->
                    <div>
                        <div class="form-group etiqueta">Día de la Marcha</div>
                        {% for day in days_list %}
                            <div class="form-check dia">
                                <input class="form-check-input" type="radio" name="event_date" id="id_event_date"
                                    value="{{ day }}" checked>
                                <label class="form-check-label" for="event_date">
                                    {{ day }}
                                </label>
                            </div>
                        {% endfor %}
                        <br />

                        <!-- INFORMACIÓN DEL DETENIDO -->
                        <p class="titulo">Ingresa la información del Detenido</p>
                        <div class="nombreAmigo form-group">
                            <label class="etiqueta">Nombres y Apellidos</label>
                            <br>
                            <input id="id_detained_fullname" type="text" pattern="[A-zñ' ]+" name="detained_fullname"
                                placeholder="Ingrese aquí" required>
                        </div>

                        <div class="form-group ubicacion">
                            <label for="inputAddress" class="etiqueta">Lugar de la Detención</label>
                            <input id="id_detained_detention_address" type="text" class="form-control"
                                name="detained_detention_address"
                                placeholder="En el cruce del Jr. de la Unión con Emancipación" required>
                        </div>

                        <div class="form-group"><label for="detained_detention_time" class="etiqueta">Hora de la
                                Detención</label>
                            <input type="time" id="id_detained_detention_time" name="detained_detention_time"
                                value="19:00" required>

                        </div>

                        <div class="col-auto">
                            <button type="submit" class="btn btn-lg btn-primary btn-block enviar">Generar Habeas
                                Corpus</button>
                        </div>
                        <div class="col-auto">
                            <code>
                                Esta página fue desarrollada pensando en los miles de peruanos que hoy estan defendiendo
                                al país en las calles. Nuestra mamá no nos deja salir a marchar pero defendemos la
                                democracia con nuestras habilidades.
                                <br /><br />
                                <strong>NADIE LE DEBE OBEDIENCIA A UN GOBIERNO USURPADOR</strong>
                                <strong>TODO PERUANO TIENE DERECHO A PROTESTAR</strong>
                                <br /><br />
                                <p>Esta página web no recopila ninguna clase de datos y si deseas ver el código fuente
                                    para asegurarte de esto, aquí dejamos el link: <a
                                        href="https://gitlab.com/davidvpe/habeame-esta"
                                        target="_blank">https://gitlab.com/davidvpe/habeame-esta</a>
                                </p>
                                <p>Realizado por:</p>
                                <p>
                                    <a href="https://twitter.com/davidvpe" target="_blank">@davidvpe</a>
                                    &nbsp;&nbsp;&nbsp;
                                    <a href="https://instagram.com/rudyminaya" target="_blank">@rudyminaya</a>
                                </p>
                            </code>
                        </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
</body>

</html>